<?php
$igit_rpwt = array( "text_show" => "<h4>Related Posts :</h4>",
					"default_no_image" => "",
					"no_related_post_text" => "No related posts found.",
					"auto_show" => "1",
					"related_post_num" => "4",
					"disable_timthumb" => "0",
					"disable_hardcrop" => "1",
					"display_thumb" => "1",
					"display_title" => "1",
					"display_full_title" => "1",
					"title_characters" => "45",
					"thumb_width" => "100",
					"thumb_height" => "100",
					"related_post_style" => "1",
					"igit_credit" => "0",
					"bk_color" => "FFFFFF",
					"bk_hover_color" => "DDDDDD",
					"bk_hover_color" => "DDDDDD",
					"fonts_family" => "Geneva",
					"fonts_size" => "12",
					"fonts_color" => "000000",
					"img_border_color" => "DDDDDD");

$igit_rpwt_default = array( "text_show" => "<h4>Related Posts :</h4>",
					"default_no_image" => "",
					"no_related_post_text" => "No related posts found.",
					"auto_show" => "1",
					"related_post_num" => "4",
					"disable_timthumb" => "0",
					"disable_hardcrop" => "1",
					"display_thumb" => "1",
					"display_title" => "1",
					"display_full_title" => "1",
					"title_characters" => "45",
					"thumb_width" => "100",
					"thumb_height" => "100",
					"related_post_style" => "1",
					"igit_credit" => "0",
					"bk_color" => "FFFFFF",
					"bk_hover_color" => "DDDDDD",
					"bk_hover_color" => "DDDDDD",
					"fonts_family" => "Geneva",
					"fonts_size" => "12",
					"fonts_color" => "000000",
					"img_border_color" => "DDDDDD");

				
?>