<?php

$igit_rpwt = array( "text_show" => "<h4>Related Posts :</h4>",
					"auto_show" => "1",
					"related_post_num" => "4",
					"display_thumb" => "1",
					"thumb_width" => "100",
					"thumb_height" => "100",
					"related_post_style" => "1",
					"igit_credit" => "1",
					"bk_color" => "FFFFFF",
					"bk_hover_color" => "DDDDDD",
					"fonts_color" => "000000",
					"img_border_color" => "DDDDDD",
					"igit_show_qtip" => "Yes",
					"igit_qtip_position" => "Top",
					"igit_qtip_solo" => "Yes",
					"igit_qtip_show" => "mouseover",
					"igit_qtip_show_effect_type" => "slide",
					"igit_qtip_show_effect_length" => "400",
					"igit_hide_qtip" => "mouseout",
					"igit_qtip_hide_effect_type" => "fade",
					"igit_qtip_hide_effect_length" => "200",
					"igit_qtip_style" => "light",
					"igit_qtip_border_width" => "0",
					"igit_qtip_border_radius" => "5",
					"igit_qtip_width" => "170",
					"igit_qtip_height" => "200");

$igit_rpwt_qtip = array( "igit_show_qtip" => "Yes",
					"igit_qtip_position" => "Bottom",
					"igit_qtip_solo" => "Yes",
					"igit_qtip_show" => "mouseover",
					"igit_qtip_show_effect_type" => "slide",
					"igit_qtip_show_effect_length" => "400",
					"igit_hide_qtip" => "mouseout",
					"igit_qtip_hide_effect_type" => "fade",
					"igit_qtip_hide_effect_length" => "200",
					"igit_qtip_style" => "cream",
					"igit_qtip_border_width" => "0",
					"igit_qtip_border_radius" => "5",
					"igit_qtip_width" => "250",
					"igit_qtip_height" => "90",
					"igit_qtip_content_char" => "200",
					"igit_qtip_content_align" => "left");				
?>